M48
; DRILL file {KiCad 8.0.5} date 2024-11-03T18:03:41-0500
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-11-03T18:03:41-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0394
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0827
%
G90
G05
T1
X3.8603Y-3.1194
X3.8603Y-3.2926
T2
X1.474Y-1.5
X1.478Y-3.15
X4.1Y-2.604
X4.21Y-1.55
M30
