M48
; DRILL file {KiCad 8.0.5} date 2024-10-19T16:39:03-0400
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-10-19T16:39:03-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0394
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0827
%
G90
G05
T1
X4.0325Y-3.1811
X4.0325Y-3.3543
T2
X1.472Y-3.42
X1.474Y-1.5
X4.21Y-1.4961
M30
